sever:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:6432/schedule_dbs
    username: root
    password: root
  cache:
    type: simple
mybatis:
  mapper-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
