/**
 * スケジュールの種類を表す列挙型
 */
export enum ScheduleEnum {
  REGULAR = 'REGULAR',
  IRREGULAR = 'IRREGULAR',
  DEFAULT = 'DEFAULT',
  COMMON_REGULAR = 'COMMON_REGULAR',
  COMMON_IRREGULAR = 'COMMON_IRREGULAR',
  COMMON_DEFAULT = 'COMMON_DEFAULT',
  FREE = 'FREE',
}
